version: "3.9"

services:
  ilifes-items-backend:
    image: ilifesregistry.azurecr.io/marketplace-backend:latest
    container_name: ilifes-items-backend
    ports:
      - "8085:80"
    volumes:
      - /var/www/html/marketplace/uploads:/var/www/html/marketplace/uploads
    restart: always

  ilifes-items-frontend:
    image: ilifesregistry.azurecr.io/marketplace-frontend:latest
    container_name: ilifes-items-frontend
    ports:
      - "3000:80"
    volumes:
      - /var/www/html/marketplace/uploads:/usr/share/nginx/html/uploads
    restart: always